db:
  image: mysql:5.6
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/logs:/var/log/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: VTmDYHFFpArB

apache:
  image: tutum/apache-php 
  volumes:
    - ./apache/sites-available:/etc/apache2/sites-available
    - ./apache/html:/app
    - ./apache/logs:/var/log/apache2
  links:
    - db
  restart: always
  environment:
    DB_HOST: db:3306
    DB_PASSWORD: VTmDYHFFpArB 

nginx:
  image: nginx
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/html:/usr/share/nginx/html
    - ./nginx/logs:/var/log/nginx
  links:
    - apache
  ports:
    - "80:80"
  restart: always
